### ISSUE TITLE
연령대별 유사도 판단 후 추천

### ISSUE THREAD

**Issue by chaeyeon-h** [pladata-encore/DA36_mini2_Bookitoki#12]
## 🌈 Success criteria

1. 연령대별 유사도 판단 후 추천
2. 카테고리 대분류 제작 후 연령대별 추천 높이기

## 👷 To-do

- [x] 연령대 column 만들기
- [x] 연령대별 읽은 횟수 count
- [x] 유사도 계산 후 추천
- [x] 카테고리 대분류 제작
- [ ] 연령별 추천+카테고리 고려
