### ISSUE TITLE
streamlit 구현 마무리 , 작가유사도 기반 책 추천 코드 수정

### ISSUE THREAD

**Issue by chaeyeon-h** [pladata-encore/DA36_mini2_Bookitoki#35]
## 🌈 Success criteria

1. 작가 유사도 기반 책 추천 코드 수정
2. streamlit 오류 해결 및 디자인 수정

## 👷 To-do

- [ ] category별 출력에서 발생하는 error 해결
- [ ] streamlit 디자인 최종 수정
- [ ] 작가유사도 기반으로 책 추천 코드 재구현
- [ ] 시현 영상 촬영
