### ISSUE TITLE
데이터 전처리

### ISSUE THREAD

**Issue by chaeyeon-h** [pladata-encore/DA36_mini2_Bookitoki#4]
## 🌈 Success criteria

1. 추천시스템 주제 정하고 사용할 데이터셋 정하기
2. 팀명 정하고 역할 분담하기
3. 데이터 전처리 

## 👷 To-do
- [x] 추천 시스템 주제 정하기 
- [x] 사용할 dataset 정하기 
- [x] 팀명 정하기 
- [x] 역할 분담하기 
- [x] 데이터 전처리 (필요한 컬럼만 추출, 결측치, encoding 작업)
